services:
  api:
    build:
      context: ..
      dockerfile: dev/Dockerfile
    container_name: messages_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - localnet
    depends_on:
      - dynamodb-local

    working_dir: /usr/src/app
    command: npm run start:dev

  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb_local
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb
    ports:
      - "8000:8000"

    networks:
      - localnet

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb_admin
    ports:
      - "8081:8001"
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
    networks:
      - localnet

volumes:
  dynamo_data:

networks:
  localnet:
    driver: bridge
